/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KjederChainSlugRouteImport } from './routes/kjeder/$chainSlug'
import { Route as ApiOpenapiDotjsonRouteImport } from './routes/api/openapi[.]json'
import { Route as ApiDocsRouteImport } from './routes/api/docs'
import { Route as KjederChainSlugIndexRouteImport } from './routes/kjeder/$chainSlug/index'
import { Route as ApiChainsIndexRouteImport } from './routes/api/chains/index'
import { Route as KjederChainSlugTimetyperRouteImport } from './routes/kjeder/$chainSlug/timetyper'
import { Route as KjederChainSlugSentreRouteImport } from './routes/kjeder/$chainSlug/sentre'
import { Route as KjederChainSlugRegionerRouteImport } from './routes/kjeder/$chainSlug/regioner'
import { Route as KjederChainSlugBrukereRouteImport } from './routes/kjeder/$chainSlug/brukere'
import { Route as ApiChainsChainIdentifierIndexRouteImport } from './routes/api/chains/$chainIdentifier/index'
import { Route as ApiChainsChainIdentifierSessionsRouteImport } from './routes/api/chains/$chainIdentifier/sessions'
import { Route as ApiChainsChainIdentifierScheduleRouteImport } from './routes/api/chains/$chainIdentifier/schedule'
import { Route as ApiChainsChainIdentifierBookingsIndexRouteImport } from './routes/api/chains/$chainIdentifier/bookings/index'
import { Route as ApiChainsChainIdentifierClassesClassIdRouteImport } from './routes/api/chains/$chainIdentifier/classes/$classId'
import { Route as ApiChainsChainIdentifierBookingsClassIdRouteImport } from './routes/api/chains/$chainIdentifier/bookings/$classId'
import { Route as ApiChainsChainIdentifierAuthLoginRouteImport } from './routes/api/chains/$chainIdentifier/auth/login'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KjederChainSlugRoute = KjederChainSlugRouteImport.update({
  id: '/kjeder/$chainSlug',
  path: '/kjeder/$chainSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: '/api/openapi.json',
  path: '/api/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api/docs',
  path: '/api/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const KjederChainSlugIndexRoute = KjederChainSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KjederChainSlugRoute,
} as any)
const ApiChainsIndexRoute = ApiChainsIndexRouteImport.update({
  id: '/api/chains/',
  path: '/api/chains/',
  getParentRoute: () => rootRouteImport,
} as any)
const KjederChainSlugTimetyperRoute =
  KjederChainSlugTimetyperRouteImport.update({
    id: '/timetyper',
    path: '/timetyper',
    getParentRoute: () => KjederChainSlugRoute,
  } as any)
const KjederChainSlugSentreRoute = KjederChainSlugSentreRouteImport.update({
  id: '/sentre',
  path: '/sentre',
  getParentRoute: () => KjederChainSlugRoute,
} as any)
const KjederChainSlugRegionerRoute = KjederChainSlugRegionerRouteImport.update({
  id: '/regioner',
  path: '/regioner',
  getParentRoute: () => KjederChainSlugRoute,
} as any)
const KjederChainSlugBrukereRoute = KjederChainSlugBrukereRouteImport.update({
  id: '/brukere',
  path: '/brukere',
  getParentRoute: () => KjederChainSlugRoute,
} as any)
const ApiChainsChainIdentifierIndexRoute =
  ApiChainsChainIdentifierIndexRouteImport.update({
    id: '/api/chains/$chainIdentifier/',
    path: '/api/chains/$chainIdentifier/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChainsChainIdentifierSessionsRoute =
  ApiChainsChainIdentifierSessionsRouteImport.update({
    id: '/api/chains/$chainIdentifier/sessions',
    path: '/api/chains/$chainIdentifier/sessions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChainsChainIdentifierScheduleRoute =
  ApiChainsChainIdentifierScheduleRouteImport.update({
    id: '/api/chains/$chainIdentifier/schedule',
    path: '/api/chains/$chainIdentifier/schedule',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChainsChainIdentifierBookingsIndexRoute =
  ApiChainsChainIdentifierBookingsIndexRouteImport.update({
    id: '/api/chains/$chainIdentifier/bookings/',
    path: '/api/chains/$chainIdentifier/bookings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChainsChainIdentifierClassesClassIdRoute =
  ApiChainsChainIdentifierClassesClassIdRouteImport.update({
    id: '/api/chains/$chainIdentifier/classes/$classId',
    path: '/api/chains/$chainIdentifier/classes/$classId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChainsChainIdentifierBookingsClassIdRoute =
  ApiChainsChainIdentifierBookingsClassIdRouteImport.update({
    id: '/api/chains/$chainIdentifier/bookings/$classId',
    path: '/api/chains/$chainIdentifier/bookings/$classId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChainsChainIdentifierAuthLoginRoute =
  ApiChainsChainIdentifierAuthLoginRouteImport.update({
    id: '/api/chains/$chainIdentifier/auth/login',
    path: '/api/chains/$chainIdentifier/auth/login',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/api/docs': typeof ApiDocsRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/kjeder/$chainSlug': typeof KjederChainSlugRouteWithChildren
  '/kjeder/$chainSlug/brukere': typeof KjederChainSlugBrukereRoute
  '/kjeder/$chainSlug/regioner': typeof KjederChainSlugRegionerRoute
  '/kjeder/$chainSlug/sentre': typeof KjederChainSlugSentreRoute
  '/kjeder/$chainSlug/timetyper': typeof KjederChainSlugTimetyperRoute
  '/api/chains/': typeof ApiChainsIndexRoute
  '/kjeder/$chainSlug/': typeof KjederChainSlugIndexRoute
  '/api/chains/$chainIdentifier/schedule': typeof ApiChainsChainIdentifierScheduleRoute
  '/api/chains/$chainIdentifier/sessions': typeof ApiChainsChainIdentifierSessionsRoute
  '/api/chains/$chainIdentifier/': typeof ApiChainsChainIdentifierIndexRoute
  '/api/chains/$chainIdentifier/auth/login': typeof ApiChainsChainIdentifierAuthLoginRoute
  '/api/chains/$chainIdentifier/bookings/$classId': typeof ApiChainsChainIdentifierBookingsClassIdRoute
  '/api/chains/$chainIdentifier/classes/$classId': typeof ApiChainsChainIdentifierClassesClassIdRoute
  '/api/chains/$chainIdentifier/bookings/': typeof ApiChainsChainIdentifierBookingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/api/docs': typeof ApiDocsRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/kjeder/$chainSlug/brukere': typeof KjederChainSlugBrukereRoute
  '/kjeder/$chainSlug/regioner': typeof KjederChainSlugRegionerRoute
  '/kjeder/$chainSlug/sentre': typeof KjederChainSlugSentreRoute
  '/kjeder/$chainSlug/timetyper': typeof KjederChainSlugTimetyperRoute
  '/api/chains': typeof ApiChainsIndexRoute
  '/kjeder/$chainSlug': typeof KjederChainSlugIndexRoute
  '/api/chains/$chainIdentifier/schedule': typeof ApiChainsChainIdentifierScheduleRoute
  '/api/chains/$chainIdentifier/sessions': typeof ApiChainsChainIdentifierSessionsRoute
  '/api/chains/$chainIdentifier': typeof ApiChainsChainIdentifierIndexRoute
  '/api/chains/$chainIdentifier/auth/login': typeof ApiChainsChainIdentifierAuthLoginRoute
  '/api/chains/$chainIdentifier/bookings/$classId': typeof ApiChainsChainIdentifierBookingsClassIdRoute
  '/api/chains/$chainIdentifier/classes/$classId': typeof ApiChainsChainIdentifierClassesClassIdRoute
  '/api/chains/$chainIdentifier/bookings': typeof ApiChainsChainIdentifierBookingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/api/docs': typeof ApiDocsRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/kjeder/$chainSlug': typeof KjederChainSlugRouteWithChildren
  '/kjeder/$chainSlug/brukere': typeof KjederChainSlugBrukereRoute
  '/kjeder/$chainSlug/regioner': typeof KjederChainSlugRegionerRoute
  '/kjeder/$chainSlug/sentre': typeof KjederChainSlugSentreRoute
  '/kjeder/$chainSlug/timetyper': typeof KjederChainSlugTimetyperRoute
  '/api/chains/': typeof ApiChainsIndexRoute
  '/kjeder/$chainSlug/': typeof KjederChainSlugIndexRoute
  '/api/chains/$chainIdentifier/schedule': typeof ApiChainsChainIdentifierScheduleRoute
  '/api/chains/$chainIdentifier/sessions': typeof ApiChainsChainIdentifierSessionsRoute
  '/api/chains/$chainIdentifier/': typeof ApiChainsChainIdentifierIndexRoute
  '/api/chains/$chainIdentifier/auth/login': typeof ApiChainsChainIdentifierAuthLoginRoute
  '/api/chains/$chainIdentifier/bookings/$classId': typeof ApiChainsChainIdentifierBookingsClassIdRoute
  '/api/chains/$chainIdentifier/classes/$classId': typeof ApiChainsChainIdentifierClassesClassIdRoute
  '/api/chains/$chainIdentifier/bookings/': typeof ApiChainsChainIdentifierBookingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/login'
    | '/api/docs'
    | '/api/openapi.json'
    | '/kjeder/$chainSlug'
    | '/kjeder/$chainSlug/brukere'
    | '/kjeder/$chainSlug/regioner'
    | '/kjeder/$chainSlug/sentre'
    | '/kjeder/$chainSlug/timetyper'
    | '/api/chains/'
    | '/kjeder/$chainSlug/'
    | '/api/chains/$chainIdentifier/schedule'
    | '/api/chains/$chainIdentifier/sessions'
    | '/api/chains/$chainIdentifier/'
    | '/api/chains/$chainIdentifier/auth/login'
    | '/api/chains/$chainIdentifier/bookings/$classId'
    | '/api/chains/$chainIdentifier/classes/$classId'
    | '/api/chains/$chainIdentifier/bookings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/login'
    | '/api/docs'
    | '/api/openapi.json'
    | '/kjeder/$chainSlug/brukere'
    | '/kjeder/$chainSlug/regioner'
    | '/kjeder/$chainSlug/sentre'
    | '/kjeder/$chainSlug/timetyper'
    | '/api/chains'
    | '/kjeder/$chainSlug'
    | '/api/chains/$chainIdentifier/schedule'
    | '/api/chains/$chainIdentifier/sessions'
    | '/api/chains/$chainIdentifier'
    | '/api/chains/$chainIdentifier/auth/login'
    | '/api/chains/$chainIdentifier/bookings/$classId'
    | '/api/chains/$chainIdentifier/classes/$classId'
    | '/api/chains/$chainIdentifier/bookings'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/login'
    | '/api/docs'
    | '/api/openapi.json'
    | '/kjeder/$chainSlug'
    | '/kjeder/$chainSlug/brukere'
    | '/kjeder/$chainSlug/regioner'
    | '/kjeder/$chainSlug/sentre'
    | '/kjeder/$chainSlug/timetyper'
    | '/api/chains/'
    | '/kjeder/$chainSlug/'
    | '/api/chains/$chainIdentifier/schedule'
    | '/api/chains/$chainIdentifier/sessions'
    | '/api/chains/$chainIdentifier/'
    | '/api/chains/$chainIdentifier/auth/login'
    | '/api/chains/$chainIdentifier/bookings/$classId'
    | '/api/chains/$chainIdentifier/classes/$classId'
    | '/api/chains/$chainIdentifier/bookings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  ApiDocsRoute: typeof ApiDocsRoute
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute
  KjederChainSlugRoute: typeof KjederChainSlugRouteWithChildren
  ApiChainsIndexRoute: typeof ApiChainsIndexRoute
  ApiChainsChainIdentifierScheduleRoute: typeof ApiChainsChainIdentifierScheduleRoute
  ApiChainsChainIdentifierSessionsRoute: typeof ApiChainsChainIdentifierSessionsRoute
  ApiChainsChainIdentifierIndexRoute: typeof ApiChainsChainIdentifierIndexRoute
  ApiChainsChainIdentifierAuthLoginRoute: typeof ApiChainsChainIdentifierAuthLoginRoute
  ApiChainsChainIdentifierBookingsClassIdRoute: typeof ApiChainsChainIdentifierBookingsClassIdRoute
  ApiChainsChainIdentifierClassesClassIdRoute: typeof ApiChainsChainIdentifierClassesClassIdRoute
  ApiChainsChainIdentifierBookingsIndexRoute: typeof ApiChainsChainIdentifierBookingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kjeder/$chainSlug': {
      id: '/kjeder/$chainSlug'
      path: '/kjeder/$chainSlug'
      fullPath: '/kjeder/$chainSlug'
      preLoaderRoute: typeof KjederChainSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/api/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs': {
      id: '/api/docs'
      path: '/api/docs'
      fullPath: '/api/docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kjeder/$chainSlug/': {
      id: '/kjeder/$chainSlug/'
      path: '/'
      fullPath: '/kjeder/$chainSlug/'
      preLoaderRoute: typeof KjederChainSlugIndexRouteImport
      parentRoute: typeof KjederChainSlugRoute
    }
    '/api/chains/': {
      id: '/api/chains/'
      path: '/api/chains'
      fullPath: '/api/chains/'
      preLoaderRoute: typeof ApiChainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kjeder/$chainSlug/timetyper': {
      id: '/kjeder/$chainSlug/timetyper'
      path: '/timetyper'
      fullPath: '/kjeder/$chainSlug/timetyper'
      preLoaderRoute: typeof KjederChainSlugTimetyperRouteImport
      parentRoute: typeof KjederChainSlugRoute
    }
    '/kjeder/$chainSlug/sentre': {
      id: '/kjeder/$chainSlug/sentre'
      path: '/sentre'
      fullPath: '/kjeder/$chainSlug/sentre'
      preLoaderRoute: typeof KjederChainSlugSentreRouteImport
      parentRoute: typeof KjederChainSlugRoute
    }
    '/kjeder/$chainSlug/regioner': {
      id: '/kjeder/$chainSlug/regioner'
      path: '/regioner'
      fullPath: '/kjeder/$chainSlug/regioner'
      preLoaderRoute: typeof KjederChainSlugRegionerRouteImport
      parentRoute: typeof KjederChainSlugRoute
    }
    '/kjeder/$chainSlug/brukere': {
      id: '/kjeder/$chainSlug/brukere'
      path: '/brukere'
      fullPath: '/kjeder/$chainSlug/brukere'
      preLoaderRoute: typeof KjederChainSlugBrukereRouteImport
      parentRoute: typeof KjederChainSlugRoute
    }
    '/api/chains/$chainIdentifier/': {
      id: '/api/chains/$chainIdentifier/'
      path: '/api/chains/$chainIdentifier'
      fullPath: '/api/chains/$chainIdentifier/'
      preLoaderRoute: typeof ApiChainsChainIdentifierIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chains/$chainIdentifier/sessions': {
      id: '/api/chains/$chainIdentifier/sessions'
      path: '/api/chains/$chainIdentifier/sessions'
      fullPath: '/api/chains/$chainIdentifier/sessions'
      preLoaderRoute: typeof ApiChainsChainIdentifierSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chains/$chainIdentifier/schedule': {
      id: '/api/chains/$chainIdentifier/schedule'
      path: '/api/chains/$chainIdentifier/schedule'
      fullPath: '/api/chains/$chainIdentifier/schedule'
      preLoaderRoute: typeof ApiChainsChainIdentifierScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chains/$chainIdentifier/bookings/': {
      id: '/api/chains/$chainIdentifier/bookings/'
      path: '/api/chains/$chainIdentifier/bookings'
      fullPath: '/api/chains/$chainIdentifier/bookings/'
      preLoaderRoute: typeof ApiChainsChainIdentifierBookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chains/$chainIdentifier/classes/$classId': {
      id: '/api/chains/$chainIdentifier/classes/$classId'
      path: '/api/chains/$chainIdentifier/classes/$classId'
      fullPath: '/api/chains/$chainIdentifier/classes/$classId'
      preLoaderRoute: typeof ApiChainsChainIdentifierClassesClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chains/$chainIdentifier/bookings/$classId': {
      id: '/api/chains/$chainIdentifier/bookings/$classId'
      path: '/api/chains/$chainIdentifier/bookings/$classId'
      fullPath: '/api/chains/$chainIdentifier/bookings/$classId'
      preLoaderRoute: typeof ApiChainsChainIdentifierBookingsClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chains/$chainIdentifier/auth/login': {
      id: '/api/chains/$chainIdentifier/auth/login'
      path: '/api/chains/$chainIdentifier/auth/login'
      fullPath: '/api/chains/$chainIdentifier/auth/login'
      preLoaderRoute: typeof ApiChainsChainIdentifierAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KjederChainSlugRouteChildren {
  KjederChainSlugBrukereRoute: typeof KjederChainSlugBrukereRoute
  KjederChainSlugRegionerRoute: typeof KjederChainSlugRegionerRoute
  KjederChainSlugSentreRoute: typeof KjederChainSlugSentreRoute
  KjederChainSlugTimetyperRoute: typeof KjederChainSlugTimetyperRoute
  KjederChainSlugIndexRoute: typeof KjederChainSlugIndexRoute
}

const KjederChainSlugRouteChildren: KjederChainSlugRouteChildren = {
  KjederChainSlugBrukereRoute: KjederChainSlugBrukereRoute,
  KjederChainSlugRegionerRoute: KjederChainSlugRegionerRoute,
  KjederChainSlugSentreRoute: KjederChainSlugSentreRoute,
  KjederChainSlugTimetyperRoute: KjederChainSlugTimetyperRoute,
  KjederChainSlugIndexRoute: KjederChainSlugIndexRoute,
}

const KjederChainSlugRouteWithChildren = KjederChainSlugRoute._addFileChildren(
  KjederChainSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  ApiDocsRoute: ApiDocsRoute,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
  KjederChainSlugRoute: KjederChainSlugRouteWithChildren,
  ApiChainsIndexRoute: ApiChainsIndexRoute,
  ApiChainsChainIdentifierScheduleRoute: ApiChainsChainIdentifierScheduleRoute,
  ApiChainsChainIdentifierSessionsRoute: ApiChainsChainIdentifierSessionsRoute,
  ApiChainsChainIdentifierIndexRoute: ApiChainsChainIdentifierIndexRoute,
  ApiChainsChainIdentifierAuthLoginRoute:
    ApiChainsChainIdentifierAuthLoginRoute,
  ApiChainsChainIdentifierBookingsClassIdRoute:
    ApiChainsChainIdentifierBookingsClassIdRoute,
  ApiChainsChainIdentifierClassesClassIdRoute:
    ApiChainsChainIdentifierClassesClassIdRoute,
  ApiChainsChainIdentifierBookingsIndexRoute:
    ApiChainsChainIdentifierBookingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
